version: '3'
services:
    wp:
        build: .docker/wp
        ports:
            - "8000:80"
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DEBUG=1
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/wp-content/themes/wordpress-theme-template
            - .docker/volumes/mu-plugins/mailhog.php:/var/www/html/wp-content/mu-plugins/mailhog.php
        user: www-data
    db:
        image: mysql:5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'wordpress'
    
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"